###
POST http://localhost:9000/api/user_register
Content-Type: application/json

{
    "email" : "sandy@gmail.com",
    "password" : "123"
}

###
GET https://backend-integrasi-user.vercel.app/api/user_read_all